services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inkingi
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6380:6379"

  backend:
    build: ../backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/inkingi
      REDIS_URL: redis://redis:6379/0
      CORS_ALLOW_ORIGINS: http://localhost:3000,http://localhost:8080
      SECRET_KEY: your-secret-key-change-in-production
    depends_on:
      - db
      - redis

  worker:
    build: ../backend
    command: celery -A app.celery_app.celery_app worker --loglevel=INFO
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/inkingi
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - backend
      - redis

  frontend:
    build: ../frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:8000"
      - "8080:8080"
    depends_on:
      - backend
      - frontend

volumes:
  db_data: 